### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by SamGreenwood1** [tbaltrushaitis/cv#52] opened 2022-10-24 23:28 UTC
![image](https://user-images.githubusercontent.com/20076209/197648969-a8a5531a-d236-4773-b331-e60e11e7bde3.png)
![image](https://user-images.githubusercontent.com/20076209/197648979-740d9998-1a45-4547-8d66-f87ee2070fdf.png)

**Comment by tbaltrushaitis** [comment] 2022-10-25 06:09
Hi @SamGreenwood1!

Looks like you need to run `make clean && make setup`.
Also you could run `npm i`

Hope this helps!

**Comment by SamGreenwood1** [comment] 2022-10-28 00:01
I tried that a number of times.

**Comment by SamGreenwood1** [comment] 2022-10-28 00:26
Is there anything I have to do to configure nginx properly? At this point I get the nginx landing page when I goto the server's IP.

**Comment by SamGreenwood1** [comment] 2022-10-28 00:34
Here's the latest log file: https://pastebin.com/EiYWUKCX

**Comment by SamGreenwood1** [comment] 2022-10-28 00:36
Is it different from last time?

**Comment by SamGreenwood1** [comment] 2022-10-28 01:20
Could you post more granular on how to install it properly?

**Comment by tbaltrushaitis** [comment] 2022-10-28 07:03
@SamGreenwood1 ,

I've look into your log file and from the line below

`error command sh -c figlet-toilet -t -f small -F border 'NPM: DEPLOY'; gulp deploy --color`
 
 I can conclude that you have not yet installed dependency **figlet-toilet**.
So as I wrote before, you need to run `make clean` and `make setup`.

**Comment by SamGreenwood1** [comment] 2022-10-28 20:45
<img width="457" alt="image" src="https://user-images.githubusercontent.com/20076209/198729457-2a7720cc-1035-41c2-bfb4-aaa36fa2edbe.png">

**Comment by tbaltrushaitis** [comment] 2022-10-29 00:09
@SamGreenwood1 ,

perfect!

Now let the ~party~ installation begins!

**Comment by SamGreenwood1** [comment] 2022-10-31 01:59
It still fails

**Comment by SamGreenwood1** [comment] 2022-10-31 02:03
<img width="604" alt="image" src="https://user-images.githubusercontent.com/20076209/198916330-d783bd5e-97c5-4eb3-88a1-abe4f2a9e30e.png">

**Comment by SamGreenwood1** [comment] 2022-10-31 02:06
nginx also seems to be broken. 
<img width="778" alt="image" src="https://user-images.githubusercontent.com/20076209/198916665-a339f7f8-2257-43c4-8bb8-5885efaec3d0.png">

**Comment by SamGreenwood1** [comment] 2022-10-31 02:23
nginx config is missing how do ou suggest I fix it?

**Comment by SamGreenwood1** [comment] 2022-11-01 19:49
gonna try installing it on another server. When installing gulp do I need to follow all the steps in the [docs](https://gulpjs.com/docs/en/getting-started/quick-start) since there's already a gulp file?

**Comment by SamGreenwood1** [comment] 2022-11-01 19:50
@tbaltrushaitis gonna try installing it on another server. When installing gulp do I need to follow all the steps in the [docs](https://gulpjs.com/docs/en/getting-started/quick-start) since there's already a gulp file?

**Comment by SamGreenwood1** [comment] 2022-11-01 20:45
setup, built, and deployed successfully on the new server but when I go to the server's IP, I still get the Nginx splash page.

**Comment by tbaltrushaitis** [comment] 2022-11-03 16:28
> <img alt="image" width="604" src="https://user-images.githubusercontent.com/20076209/198916330-d783bd5e-97c5-4eb3-88a1-abe4f2a9e30e.png">

Please provide output of `make setup` command.

Thank you!

**Comment by tbaltrushaitis** [comment] 2022-11-03 16:34
> @tbaltrushaitis gonna try installing it on another server. When installing gulp do I need to follow all the steps in the [docs](https://gulpjs.com/docs/en/getting-started/quick-start) since there's already a gulp file?

You just need to have gulp installed globally or local.

**Comment by tbaltrushaitis** [comment] 2022-11-03 16:37
> setup, built, and deployed successfully on the new server but when I go to the server's IP, I still get the Nginx splash page.

Ahh, cool!
Describibg of how to configure nginx to serve from web directories is out of scope for this repo. 
But I can suggest that you need to configure virtual host for CV inside of nginx. Btw, [here](https://github.com/tbaltrushaitis/cv/blob/master/etc/nginx/sites-available/010-cv) you can find an example ;-)

**Comment by SamGreenwood1** [comment] 2022-11-03 16:50
<img width="533" alt="image" src="https://user-images.githubusercontent.com/20076209/199783925-e64bcb2c-0d2c-413a-8656-fddaae68ca40.png">

**Comment by SamGreenwood1** [comment] 2022-11-03 16:51
> > @tbaltrushaitis gonna try installing it on another server. When installing gulp do I need to follow all the steps in the [docs](https://gulpjs.com/docs/en/getting-started/quick-start) since there's already a gulp file?
> 
> You just need to have gulp installed globally or local.

both

**Comment by tbaltrushaitis** [comment] 2022-11-03 17:12
> Does Nginx need to be globally installed?

Nginx is not part of node/npm. It whould be installed as service in your OS.

**Comment by tbaltrushaitis** [comment] 2022-11-03 17:15
Closing as reporter confirmed issue resolved for him.

**Closed by tbaltrushaitis** 2022-11-03 17:15 UTC
Labels: help wanted, dependencies

**Comment by SamGreenwood1** [comment] 2022-11-03 17:20
It deploys successfully but the webpage errors out. What should be in /var/www/html?

**Comment by SamGreenwood1** [comment] 2022-11-03 17:52
I noticed that there's a reference to `/var/www/html/cv.git/webroot` in `~/cv/etc/nginx/sites-available/010-cv` but, that file doesn't exist on my server. Is `cv.git` supposed to be a link to the cv directory?

**Comment by tbaltrushaitis** [comment] 2022-11-04 10:54
> @tbaltrushaitis I noticed that there's a reference to `/var/www/html/cv.git/webroot` in `~/cv/etc/nginx/sites-available/010-cv` but, that file doesn't exist on my server. Is `cv.git` supposed to be a link to the cv directory?

In my configuration cv directory is `/var/www/html/cv.git` and nginx pointed ti `webroot` dir inside of it (as `Make` build project distro from sources into it).


> 2:37 PM ET: just tried that it didn't help. I realized that there's an ssl error when I try to access it over HTTPS. are your certs in the repo?

You should setup certs by your own at your server (e.g. with [certbot](https://certbot.eff.org/)). They should never be committed into git repo.

**Comment by SamGreenwood1** [comment] 2022-11-05 15:57
so the 

> > @tbaltrushaitis I noticed that there's a reference to `/var/www/html/cv.git/webroot` in `~/cv/etc/nginx/sites-available/010-cv` but, that file doesn't exist on my server. Is `cv.git` supposed to be a link to the cv directory?
> 
> In my configuration cv directory is `/var/www/html/cv.git` and nginx pointed ti `webroot` dir inside of it (as `Make` build project distro from sources into it).

cv directory itself is in `/var/www/html`?

**Comment by tbaltrushaitis** [comment] 2022-11-08 11:52
> so the
> 
> > > @tbaltrushaitis I noticed that there's a reference to `/var/www/html/cv.git/webroot` in `~/cv/etc/nginx/sites-available/010-cv` but, that file doesn't exist on my server. Is `cv.git` supposed to be a link to the cv directory?
> > 
> > 
> > In my configuration cv directory is `/var/www/html/cv.git` and nginx pointed ti `webroot` dir inside of it (as `Make` build project distro from sources into it).
> 
> cv directory itself is in `/var/www/html`?

Yep. But its not the rule. It can be anywhere you want.
