### ISSUE TITLE
Unsupported platform 

### ISSUE THREAD

**Issue by genciT5** [tbaltrushaitis/cv#16] opened 2020-01-28 00:50 UTC
As I see from the live demo, it's obvious that you've done a great work!
However, when I'm trying to setup the project, after cloning it to my computer, I'm getting an error after typing the **$ make setup** command:
_"npm ERR! notsup Unsupported platform for cv@0.2.4: wanted {"os":"linux,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})"_
I'm using Mac machine.  Any possibilities of running the app inside mac computer?

**Comment by tbaltrushaitis** [comment] 2020-01-28 22:25
Hi @genciT5 !

Thank you for your positive feedback! 

To have scripts run on Mac just add "**darwin**" into array of permitted OS on line 24 of `package.json` file:

```
<...>
, "os": ["linux", "win32", "darwin"]
<...>
```

Enjoy! ;-)

**Comment by genciT5** [comment] 2020-01-28 22:51
Thank you, it worked. 

After trying to execute **$ make deploy** command I am getting this error:
"_npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cv@0.2.4 deploy: `echo [DEPLOY]; gulp deploy --color`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cv@0.2.4 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above._"

Any idea how could this error be fixed?

**Comment by tbaltrushaitis** [comment] 2020-01-29 18:48
Hi!

Not enough info about what is the error itself. Please post 20-30 lines of log that are before currently posted or attach a full log output.

Thank you!

**Comment by genciT5** [comment] 2020-01-31 17:45
Down below is a screenshot of my terminal:
<img width="568" alt="Screenshot 2020-01-31 at 6 43 05 PM" src="https://user-images.githubusercontent.com/46035737/73561593-8ad1ba00-4459-11ea-9007-02fb234294d0.png">

And here is the result of the log file:

_0 _info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'deploy' ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle cv@0.2.4~predeploy: cv@0.2.4
6 info lifecycle cv@0.2.4~deploy: cv@0.2.4
7 verbose lifecycle cv@0.2.4~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle cv@0.2.4~deploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Genci/cv/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/Genci/.rvm/bin:/Users/Genci/.rvm/bin
9 verbose lifecycle cv@0.2.4~deploy: CWD: /Users/Genci/cv
10 silly lifecycle cv@0.2.4~deploy: Args: [ '-c', 'echo [DEPLOY]; gulp deploy --color' ]
11 silly lifecycle cv@0.2.4~deploy: Returned: code: 1  signal: null
12 info lifecycle cv@0.2.4~deploy: Failed to exec deploy script
13 verbose stack Error: cv@0.2.4 deploy: `echo [DEPLOY]; gulp deploy --color`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid cv@0.2.4
15 verbose cwd /Users/Genci/cv
16 verbose Darwin 19.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
18 verbose node v12.14.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error cv@0.2.4 deploy: `echo [DEPLOY]; gulp deploy --color`
22 error Exit status 1
23 error Failed at the cv@0.2.4 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]__

**Comment by tbaltrushaitis** [comment] 2020-01-31 18:08
Hi!

Unfortunately, neither screenshot nor logfile itself does not have and valuable information about the root cause of the issue. :-( 
Maybe.. gulp is not installed or something like that?

Sorry, can't help there...

**Comment by tbaltrushaitis** [comment] 2020-02-09 01:55
@genciT5 ,

can this be marked as **solved** and **closed**?

Thank you!

**Closed** 2020-02-12 17:13 UTC
Labels: enhancement, help wanted, question
